var boxes = {
	'box1':{
		'activities':[ 
			'Learn how things grow and stay alive.',
			'Make the best use of the earth’s natural resources.',
			'Hunt and/or fish.',
			'Protect the environment.',
			'Be outdoors in all kinds of weather.',
			'Plan, budget, and keep records.',
			'Operate machines and keep them in good repair.',
		],
		'qualities':[ 
			'Self-reliant',
			'Nature lover',
			'Physical active',
			'Planner',
			'Creative problem solver',
		],
		'subjects':[
			'Math',
			'Life sciences',
			'Earth sciences',
			'Chemistry',
			'Agriculture',
		]
	},
	'box2':{
		'activities':[ 
			'Read and follow blueprints and/or instructions.',
			'Picture in my mind what a finished product looks like.',
			'Work with my hands.',
			'Perform work that requires precise results.',
			'Solve technical problems.',
			'Visit and learn from beautiful, historic, or interesting buildings.',
			'Follow logical, step-by-step procedures.',
		],
		'qualities':[ 
			'Curious',
			'Good at following directions',
			'Pay attention to detail',
			'Good at visualizing possibilities',
			'Patient and persistent',
		],
		'subjects':[
			'Math',
			'Drafting',
			'Physical Sciences',
			'Construction Trades',
			'Electrical Trades (Heat, Air Conditioning, and Refrigeration)',
			'Technology education',
		]
	},
	'box3':{
		'activities':[ 
			'Use my imagination to communicate new information to others.',
			'Perform in front of others.',
			'Read and write.',
			'Play a musical instrument.',
			'Perform creative, artistic activities.',
			'Use video and recording technology.',
			'Design brochures and posters.',
		],
		'qualities':[ 
			'Creative and imaginative',
			'Good communicator/ vocabulary',
			'Curious about new technology',
			'Relate well to feelings and thoughts of others',
			'Determined/tenacious',
		],
		'subjects':[
			'Art/Graphic design',
			'Music',
			'Speech and Drama',
			'Journalism/Literature',
			'Audiovisual Technologies',
		]
	},
	'box4':{
		'activities':[ 
			'Perform routine, organized activities but can be flexible.',
			'Work with numbers and detailed information.',
			'Be the leader in a group.',
			'Make business contact with people.',
			'Work with computer programs.',
			'Create reports and communicate ideas.',
			'Plan my work and follow instructions without close supervision.',
		],
		'qualities':[ 
			'Organized',
			'Practical and logical',
			'Patient',
			'Tactful',
			'Responsible',
		],
		'subjects':[
			'Computer Applications/ Business and Information Technology ',
			'Accounting ',
			'Math ',
			'English ',
			'Economics ',
		],
	},
	'box5':{
		'activities':[ 
			'Communicate with different types of people.',
			'Help others with their homework or to learn new things.',
			'Go to school.',
			'Direct and plan activities for others.',
			'Handle several responsibilities at once.',
			'Acquire new information.',
			'Help people overcome challenges.',
		],
		'qualities':[ 
			'Friendly',
			'Decision maker',
			'Helpful',
			'Innovative/Inquisitive',
			'Good listener',
		],
		'subjects':[
			'Language Arts',
			'Social Studies',
			'Math',
			'Science',
			'Psychology',
		],
	},
	'box6':{
		'activities':[ 
			'Work with numbers.',
			'Work to meet a deadline.',
			'Make predictions based on existing facts. Have a framework of rules by which to operate.',
			'Analyze financial information and interpret it to others.',
			'Handle money with accuracy and reliability.',
			'Take pride in the way I dress and look.',
		],
		'qualities':[ 
			'Trustworthy',
			'Orderly',
			'Self-confident',
			'Logical',
			'Methodical or efficient',
		],
		'subjects':[
			'Accounting',
			'Math',
			'Economics',
			'Banking/Financial Services',
			'Business Law',
		],
	},
	'box7':{
		'activities':[ 
			'Be involved in politics.',
			'Negotiate, defend, and debate ideas and topics.',
			'Plan activities and work cooperatively with others.',
			'Work with details.',
			'Perform a variety of duties that may change often.',
			'Analyze information and interpret it to others.',
			'Travel and see things that are new to me.',
		],'qualities':[ 
			'Good communicator',
			'Competitive',
			'Service minded',
			'Well organized',
			'Problem solver',
		],'subjects':[
			'Government',
			'Language Arts',
			'History',
			'Math',
			'Foreign Language',
		],
	},
	'box8':{
		'activities':[ 
			'Work under pressure.',
			'Help sick people and animals.',
			'Make decisions based on logic and information.',
			'Participate in health and science classes.',
			'Respond quickly and calmly in emergencies.',
			'Work as a member of a team.',
			'Follow guidelines precisely and meet strict standards of accuracy.',
		],
		'qualities':[ 
			'Compassionate and caring',
			'Good at following directions',
			'Conscientious and careful',
			'Patient',
			'Good listener',
		],'subjects':[
			'Biology Sciences',
			'Chemistry',
			'Math',
			'Occupational Health classes',
			'Language Arts',
		]
	},
	'box9':{
		'activities':[ 
			'Investigate new places and activities.',
			'Work with all ages and types of people.',
			'Organize activities in which other people enjoy themselves.',
			'Have a flexible schedule.',
			'Help people make up their minds.',
			'Communicate easily, tactfully, and courteously.',
			'Learn about other cultures.',
		],
		'qualities':[
			'Tactful',
			'Self-motivated',
			'Works well with others',
			'Outgoing',
			'Slow to anger',
		],
		'subjects':[
			'Language Arts/Speech',
			'Foreign Language',
			'Social Studies',
			'Marketing',
			'Food Service',
		],
	},
	'box10':{
		'activities':[ 
			'Care about people, their needs, and their problems.',
			'Participate in community service and/or volunteering.',
			'Listen to people’s viewpoints',
			'Help people be their best.',
			'Work with people from preschool age to old age.',
			'Think of new ways to new things.',
			'Make friends with different kinds of people.',
		],
		'qualities':[
			'Good communicator/good listener',
			'Caring',
			'Non-materialistic',
			'Uses intuition and logic',
			'Non-judgmental',
		],
		'subjects':[
			'Language Arts',
			'Psychology',
			'Family and Consumer sciences',
			'Finance',
			'Foreign Language',
		],
	},
	'box11':{
		'activities':[ 
			'Work with computers.',
			'Reason clearly and logically to solve complex problems.',
			'Use machines, techniques, and processes.',
			'Read technical materials and diagrams and solve technical problems.',
			'Adapt to change.',
			'Play video games and figure out how they work.',
			'Concentrate for long periods without being distracted.',
		],
		'qualities':[
			'Logic/analytical thinker',
			'See details in the big picture',
			'Persistent',
			'Good concentration skills',
			'Precise and accurate.',
		],
		'subjects':[
			'Math',
			'Science',
			'Computer Tech/Applications',
			'Communications',
			'Graphic Design',
		],
	},
	'box12':{
		'activities':[ 
			'Work under pressure or in the face of danger.',
			'Make decisions based on my own observations.',
			'Interact with other people.',
			'Be in positions of authority.',
			'Respect rules and regulations.',
			'Debate and win arguments.',
			'Observe and analyze people’s behavior.',
		],'qualities':[
			'Adventurous',
			'Dependable',
			'Community-minded',
			'Decisive',
			'Optimistic',
		],'subjects':[
			'Language Arts',
			'Psychology/ Sociology',
			'Government/History',
			'Law Enforcement',
			'First Aid/First Responder',
		],
	},
	'box13':{
		'activities':[
			'Work with my hands and learn that way.',
			'Put things together.',
			'Do routine, organized, and accurate work.',
			'Perform activities that produce tangible results.',
			'Use hand and power tools to operate equipment/machinery.',
			'Visualize objects in three dimensions from flat drawings.',
		],
		'qualities':[ 
			'Practical',
			'Observant',
			'Physically active',
			'Step-by-step thinker',
			'Coordinated',
		],
		'subjects':[
			'Math/Geometry',
			'Chemistry',
			'Trade and Industry courses',
			'Physics',
			'Language Arts',
		],
	},
	'box14':{
		'activities':[ 
			'Shop and go to the mall.',
			'Be in charge.',
			'Make displays and promote ideas.',
			'Give presentation enjoy public speaking.',
			'Persuade people to buy products or to participate in activities.',
			'Communicate my ideas to other people.',
			'Take advantage of opportunities to make extra money.',
		],
		'qualities':[ 
			'Enthusiastic',
			'Competitive',
			'Creative',
			'Self-motivated',
			'Persuasive',
		],
		'subjects':[
			'Math',
			'Trade and Industry courses',
			'Physical Sciences',
			'Economics Foreign Language',
		],
	},
	'box15':{
		'activities':[ 
			'Interpret formulas.',
			'Find the answers to questions.',
			'Work in a laboratory.',
			'Figure out how things work and investigate new things.',
			'Explore new technology.',
			'Experiment to find the best way to do something.',
			'Pay attention to details and help things be precise.',
		],
		'qualities':[
			'Detail oriented',
			'Inquisitive',
			'Objective',
			'Methodical',
			'Mechanically inclined',
		],
		'subjects':[
			'Math Science',
			'Drafting/Computer-Aided Drafting',
			'Electronics/Computer Networking',
			'Technical Classes/Technology Education',
		],
	},
	'box16':{
		'activities':[ 
			'Travel',
			'See well and have quick reflexes.',
			'Solve mechanical problems.',
			'Design efficient processes.',
			'Anticipate needs and prepare to meet them.',
			'Drive or ride.',
			'Move things from one place to another.',
		],
		'qualities':[
			'Realistic',
			'Mechanical',
			'Coordinated',
			'Observant',
			'Planner',
		],
		'subjects':[
			'Math',
			'Trade and Industry courses',
			'Physical Sciences',
			'Economics',
			'Foreign Languages',
		]
	}
};